### ISSUE TITLE
Would you please tell me how did you generate the `vectorList.json` file ?

### ISSUE THREAD

**Issue by CoinCheung** [StephanieWyt/HGCN-JE-JR#2]
I noticed that there are 38960 vectors in the `zh_vectorList.json` file, and the numbers of entities in `ent_ids_1` and `ent_ids_2` are 29887 and 34459. So would you tell me what is the specific meanings of the json file and how did you generate it ?

**Comment by StephanieWyt** [comment]
Hi,
Thanks for your interest in our work! The vectors in the json file are the initial embeddings of the 38960 entities (19388 entities in ent_ids_1 and 19572 entities in ent_ids_2) in DBP15K_ZH-EN dataset. We translate non-English entity names to English via Google Translate, and then use pre-trained English word vectors glove.840B.300d to construct the initial representations for entities.

**Comment by CoinCheung** [comment]
Thanks for replying !! I am closing this.
